### ISSUE TITLE
Enhancement request: rewrite this as a Thumbnail Generator for Spotlight

### ISSUE THREAD

**Issue by DavidPhillipOster** [DavidPhillipOster/gcodeToThumbnail#1]
If this were a Thumbnail Generator for Spotlight then no change for PrusaSlicer would be needed and it would show the custom icon even if the .gcode file were moved to a EXFAT or FAT filesystem.

**Comment by matthewjschultz** [comment]
Understanding that I'm veering off the intended course… between OctoPrint and PrusaLink I find myself rarely generating .gcode files that live on my Mac. I just publish directly to the printer which means the .gcode files only live on the Mini's thumb drive. What would be helpful is generating previews for 3MF files. (Unless this happens already and my install isn't working as advertised.) 

Just a thought.

**Comment by DavidPhillipOster** [comment]
Thank you. I've learned some things since I wrote the app.

PrusaSlicer .3MF files already contain a thumbnail. I will write a Spotlight Plugin that will cause Finder to show those thumbnail as icons.

That same spotlight plugin will allow gcode thumbnails to appear as Finder icons, even when the .gcode files are on the Mini's thumb drive.

Please be aware of https://github.com/prusa3d/PrusaSlicer/issues/6322 : some Octoprint users have had problems with Octoprint timing out as it tries to skip large thumbnails.

**Comment by matthewjschultz** [comment]
David, That would be ah-maze-ing. 

Thank you!

**Comment by DavidPhillipOster** [comment]
Here's a working version: https://github.com/DavidPhillipOster/ThumbHost3mf - it works on my machine, and I want to learn if it works for other people. It will cause Finder to show all PrusaSlicer .3mf files with a custom icon, and .gcode files that contain thumbnail data will show with a custom icon
